package com.abhi.authProject.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.beans.factory.annotation.Autowired;

@Configuration
public class EmergencyAdminFix {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Bean
    CommandLineRunner fixDatabaseSchema() {
        return args -> {
            System.out.println("🚨 EMERGENCY DB PATCHER: Checking Schema Health...");

            // 1. Fix Users Table (Add 'batch' if missing)
            try {
                // Set statement timeout to 0 (unlimited) and add column in one go
                jdbcTemplate.execute(
                        "SET statement_timeout = 0; ALTER TABLE users ADD COLUMN IF NOT EXISTS batch VARCHAR(255);");
                System.out.println("✅ Checked/Added 'batch' column to 'users' (Combined Statement)");
            } catch (Exception e) {
                System.err.println("⚠️ Error patching users table: " + e.getMessage());
                // Alternate attempt without IF NOT EXISTS
                try {
                    jdbcTemplate.execute("ALTER TABLE users ADD COLUMN batch VARCHAR(255)");
                } catch (Exception e2) {
                    // It might already exist now
                }
            }

            // 2. Create id_card_image table manually (Hibernate failing to create it?)
            try {
                jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS id_card_image (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "name VARCHAR(255), " +
                        "type VARCHAR(255), " +
                        "data OID)"); // Postgres LOB usually OID or BYTEA. Hibernate usually maps @Lob to OID in
                                      // Postgres sometimes.
                // Actually, let's use BYTEA for logic, but Hibernate might expect OID.
                // Safer to let Hibernate handle it if possible, but if table is missing...
                // If I create it, Hibernate might complain if types mismatch.
                // Better strategy: Add columns to existing tables first.
                // Re-think: The error says "relation id_card_image does not exist".
                // I will try to create it.
                jdbcTemplate.execute(
                        "CREATE TABLE IF NOT EXISTS id_card_image (id BIGSERIAL PRIMARY KEY, name VARCHAR(255), type VARCHAR(255), data BYTEA)");
                System.out.println("✅ Checked/Created 'id_card_image' table");
            } catch (Exception e) {
                System.err.println("⚠️ Error creating id_card_image table: " + e.getMessage());
            }

            // 3. Fix Student Profiles (Add new columns)
            try {
                jdbcTemplate.execute("ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS college_name VARCHAR(255)");
                jdbcTemplate
                        .execute("ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS aadhar_card_url VARCHAR(255)");
                jdbcTemplate
                        .execute("ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS admit_card_url VARCHAR(255)");
                // Add FK columns
                jdbcTemplate.execute("ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS id_card_image_id BIGINT");
                jdbcTemplate.execute("ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS aadhar_image_id BIGINT");
                jdbcTemplate
                        .execute("ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS admit_card_image_id BIGINT");
                System.out.println("✅ Checked/Added columns to 'student_profiles'");
            } catch (Exception e) {
                System.err.println("⚠️ Error patching student_profiles table: " + e.getMessage());
            }

            System.out.println("✅ Schema Patching Complete. Hibernate should validate now.");
        };
    }
}
