package com.abhi.authProject.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.Date; // For the 'uploadedAt' timestamp

@Entity // Marks this Java object as an entity that maps to a database table
@Table(name = "papers") // Explicitly names the table in your PostgreSQL database
public class Paper {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increments the ID in PostgreSQL
    private Long id; // Use Long for auto-incrementing primary keys in JPA

    private String title;
    private String subject; // e.g., "aptitude", "coding", "reasoning"
    private int year;
    private int semester; // 1 to 8
    private String branch; // e.g., "CSE", "MCA"
    private String company; // e.g., "TCS", "Infosys"
    private String category; // e.g., "Mid-Sem", "End-Sem", "Internal"
    private String pdfUrl; // Path to the uploaded file on the server
    private Date uploadedAt; // Auto-generated timestamp

    // --- Constructors ---
    // Default constructor (required by JPA)
    public Paper() {
        this.uploadedAt = new Date(); // Automatically set current time when a Paper object is created
    }

    // Constructor for creating a new paper (ID is generated by the database)
    public Paper(String title, String subject, int year, int semester, String branch, String company, String category,
            String pdfUrl) {
        this.title = title;
        this.subject = subject.toLowerCase();
        this.year = year;
        this.semester = semester;
        this.branch = branch;
        this.company = company;
        this.category = category;
        this.pdfUrl = pdfUrl;
        this.uploadedAt = new Date();
    }

    // --- Getters and Setters ---
    // Essential for JPA to map database rows to Java objects and for JSON
    // serialization.

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public int getSemester() {
        return semester;
    }

    public void setSemester(int semester) {
        this.semester = semester;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getPdfUrl() {
        return pdfUrl;
    }

    public void setPdfUrl(String pdfUrl) {
        this.pdfUrl = pdfUrl;
    }

    public Date getUploadedAt() {
        return uploadedAt;
    }

    public void setUploadedAt(Date uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    @Override
    public String toString() {
        return "Paper{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", subject='" + subject + '\'' +
                ", branch='" + branch + '\'' +
                ", year=" + year +
                ", semester=" + semester +
                ", company='" + company + '\'' +
                ", category='" + category + '\'' +
                ", pdfUrl='" + pdfUrl + '\'' +
                ", uploadedAt=" + uploadedAt +
                '}';
    }
}